# Generated by Django 2.1.2 on 2018-10-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0002_auto_20181006_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedetail',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='codedetail',
            name='x',
            field=models.CharField(max_length=100),
        ),
    ]
