# Generated by Django 2.1.2 on 2018-10-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApi', '0003_auto_20181006_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codedetail',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
